config/routes.rb
Rails.application.routes.draw do
  get 'users/show'

  devise_for :users
  resources :users, :only => [:show], :path => 'u' do
    resources :collections, :except => [:index, :new], :path => '/' do
      resources :texts, :except => [:index, :new]

      member do
        get 'play'
      end
    end
  end
  resources :collections, :only => [:index]

  root 'welcome#index'

end

app/models/collection.rb
class Collection < ActiveRecord::Base
  belongs_to :user
  has_many :texts, dependent: :destroy
  accepts_nested_attributes_for :texts

  validates :title,
    :presence => true,
    :uniqueness => {
      :scope => [:user_id],
      :case_sensitive => false
    },
    :exclusion => {
      # Now, it doesn't use `new` by system but keep it reserved for future
      :in => %w(new),
      :message => "You cannot use %{value} because it's a reserved word"
    }

  def self.find(query)
    self.find_by_title(query) || super(query)
  end

  def to_param
    "#{self.title}"
  end

  def self.search(query)
    if query
      Collection.where(['title LIKE ? or description LIKE ?', "%#{query}%", "%#{query}%"])
    else
      Collection.all
    end
  end
end

app/controllers/collections_controller.rb
class CollectionsController < ApplicationController
  before_action :set_collection, only: [:show, :edit, :update, :destroy, :play]
  before_action :set_user, except: [:index]
  before_action :authenticate_user, only: [:create, :edit, :update, :destroy]

  def play
  end

  # GET /collections
  # GET /collections.json
  def index
    @collections = Collection.search(params[:query])
  end

  # GET /collections/1
  # GET /collections/1.json
  def show
    @texts = @collection.texts
    # To create texts
    @text = Text.new
    @text.collection = @collection

    respond_to do |format|
      format.html
      format.json {render :json => @collection.as_json(:include => :texts)}
    end
  end

  # GET /collections/1/edit
  def edit
  end

  # POST /collections
  # POST /collections.json
  def create
    @collection = Collection.new(collection_params)

    respond_to do |format|
      if @collection.save
        format.html { redirect_to user_collection_path(@collection.user, @collection), notice: 'Collection was successfully created.' }
        format.json { render :show, status: :created, location: @collection }
      else
        format.html { render :new }
        format.json { render json: @collection.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /collections/1
  # PATCH/PUT /collections/1.json
  def update
    respond_to do |format|
      if @collection.update(collection_params)
        format.html { redirect_to user_collection_path(@collection.user, @collection), notice: 'Collection was successfully updated.' }
        format.json { render :show, status: :ok, location: @collection }
      else
        format.html { render :edit }
        format.json { render json: @collection.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /collections/1
  # DELETE /collections/1.json
  def destroy
    @collection.destroy
    respond_to do |format|
      format.html { redirect_to user_collections_url, notice: 'Collection was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_collection
      @collection = Collection.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def collection_params
      params.require(:collection).permit(:title, :description, :user_id)
    end

    def set_user
      @user = User.find(params[:user_id])
    end

    def authenticate_user
      @user = User.find(params[:user_id])
      if @user != current_user
        redirect_to user_collections_url, notice: 'You have no permission'
      end
    end
end

app/helpers/collections_helper.rb
module CollectionsHelper
end

app/views/collections/_form.html.erb
<%= form_for([@user, @collection]) do |f| %>
  <% if @collection.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@collection.errors.count, "error") %> prohibited this collection from being saved:</h2>

      <ul>
      <% @collection.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
      <%= f.text_field :title, :class => 'mdl-textfield__input' %>
      <%= f.label :title, :class => 'mdl-textfield__label' %>
    </div>
  </div>
  <div>
    <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
      <%= f.text_area :description, :class => 'mdl-textfield__input' %>
      <%= f.label :description, :class => 'mdl-textfield__label' %>
    </div>
  </div>
  <div class="field">
    <%= f.hidden_field :user_id%>
  </div>
  <div class="actions">
    <%= f.submit 'Submit', :class => 'mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--accent'  %>
  </div>
<% end %>

app/views/collections/edit.html.erb
<h2>Editing: <%= @user.username %> / <%= @collection.title %></h2>

<%= render 'form' %>

<%= link_to 'Show', user_collection_path(@collection.user, @collection) %> |
<%= link_to 'Back', user_collections_path %>

app/views/collections/index.html.erb
<h2>Listing Collections</h2>

<%= form_tag collections_path, :method => 'get' do %>
  <div>
    <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
      <%= text_field_tag :query, params[:query], :class => 'mdl-textfield__input' %>
      <label for="query" class="mdl-textfield__label">
        <i class="material-icons">search</i>
      </label>
    </div>
  </div>
<% end %>

<% if not @collections.present? %>
  Not found
<% else %>
  <table class="mdl-data-table mdl-js-data-table">
    <thead>
      <tr>
        <th class='mdl-data-table__cell--non-numeric'>User</th>
        <th class='mdl-data-table__cell--non-numeric'>Title</th>
        <th class='mdl-data-table__cell--non-numeric'>Description</th>
        <th colspan="2"></th>
      </tr>
    </thead>

    <tbody>
      <% @collections.each do |collection| %>
        <tr>
          <td class='mdl-data-table__cell--non-numeric'><%= link_to collection.user.username, user_path(collection.user) %></td>
          <td class='mdl-data-table__cell--non-numeric'><%= link_to collection.title, user_collection_path(collection.user, collection) %></td>
          <td class='mdl-data-table__cell--non-numeric'><%= collection.description %></td>
          <% if user_signed_in? and collection.user == current_user %>
            <td><%= link_to 'Edit', edit_user_collection_path(collection.user, collection) %></td>
            <td><%= link_to 'Destroy', user_collection_path(collection.user, collection), method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

app/views/collections/play.html.erb
<h2> Play! <%= link_to @user.username, user_path(@user) %> / <%= link_to @collection.title, user_collection_path(@user, @collection) %></h2>

<button id='game-start-button' class='mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--accent'>Start</button>

<div id='game-area' style='display: none;'>
  <div id='game-problem-text-field'>
    <p id='game-problem-text'>
      Here is the text
    </p>
  </div>

  <div>
    <div class='game-field mdl-textfield mdl-js-textfield'>
      <textarea id='game-user-input' class='mdl-textfield__input' rows=3></textarea>
      <label for='game-user-input' class='mdl-textfield__label'>Input</label>
    </div>
  </div>
</div>

<div id='game-result-area' style='display: none;'>
  <p>
    Game End!
  </p>

  <table class="mdl-data-table mdl-js-data-table">
    <thead>
      <tr>
        <th>Title</th>
        <th>Body</th>
        <th>Description</th>
      </tr>
    </thead>

    <tbody>
      <% @collection.texts.each do |text| %>
        <tr>
          <td><%= link_to text.title, user_collection_text_path(@user, @collection, text) %></td>
          <td><%= text.body %></td>
          <td><%= text.description %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <%= link_to 'Back', user_collections_path, :class => 'mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect' %>
</div>

app/views/collections/show.html.erb
<h2><%= @user.username %> / <%= @collection.title %></h2>


<p>
  <%= link_to 'Play!', play_user_collection_path(@user, @collection), :class => 'mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--accent' %>
</p>

<p>
  <strong>Description:</strong>
  <%= @collection.description %>
</p>

<% if not @texts.present? %>
  No texts registered in this collection
<% else %>
  <table class="mdl-data-table mdl-js-data-table">
    <thead>
      <tr>
        <th class='mdl-data-table__cell--non-numeric'>Title</th>
        <th class='mdl-data-table__cell--non-numeric'>Body</th>
        <th class='mdl-data-table__cell--non-numeric'>Description</th>
        <% if user_signed_in? and @user == current_user %>
          <th colspan="2"></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% @texts.each do |text| %>
        <tr>
          <td class='mdl-data-table__cell--non-numeric'><%= link_to text.title, user_collection_text_path(@user, @collection, text) %></td>
          <td class='mdl-data-table__cell--non-numeric'><%= truncate(text.body, omission: '...', length: 15) %></td>
          <td class='mdl-data-table__cell--non-numeric'><%= truncate(text.description, omission: '...', length: 15) %></td>
          <% if user_signed_in? and @user == current_user %>
            <td><%= link_to 'Edit', edit_user_collection_text_path(@user, @collection, text) %></td>
            <td><%= link_to 'Destroy', user_collection_text_path(@user, @collection, text), method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>


<% if user_signed_in? and @user == current_user %>
  <h3>New Text</h3>
  <%= render 'texts/form' %>

  <%= link_to 'Edit', edit_user_collection_path(@collection.user, @collection) %> |
<% end %>

<%= link_to 'Back', user_collections_path %>