config/routes.rb
Rails.application.routes.draw do
  get 'users/show'

  devise_for :users
  resources :users, :only => [:show], :path => 'u' do
    resources :collections, :except => [:index, :new], :path => '/' do
      resources :texts, :except => [:index, :new]

      member do
        get 'play'
      end
    end
  end
  resources :collections, :only => [:index]

  root 'welcome#index'

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  before_action :set_newest_collections

  def index
    @n_of_collections = Collection.count
    @n_of_users = User.count
  end

  private
    def set_newest_collections
      @newest_collections = Collection.order("created_at DESC").limit(10)
    end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/index.html.erb
<% if @newest_collections.present? %>
  <h2>Newest collections</h2>

  <table cellspacing="0" class="mdl-data-table mdl-js-data-table">
  <tr>
    <td class='mdl-data-table__cell--non-numeric'>User</td>
    <td class='mdl-data-table__cell--non-numeric'>Title</td>
    <td class='mdl-data-table__cell--non-numeric'>Description</td>
    <td class='mdl-data-table__cell--non-numeric'>created at</td>
  </tr>
  <% @newest_collections.each do |collection| %>
    <tr>
      <td class='mdl-data-table__cell--non-numeric'><%= link_to truncate(collection.user.username, omission: '...', length: 15), user_path(collection.user) %></td>
      <td class='mdl-data-table__cell--non-numeric'><%= link_to truncate(collection.title, omission: '...', length: 15), user_collection_path(collection.user, collection) %></td>
      <td class='mdl-data-table__cell--non-numeric'><%= truncate(collection.description, omission: '...', length: 15) %></td>
      <td class='mdl-data-table__cell--non-numeric'><%= collection.created_at %></td>
    </tr>
  <% end %>
  </table>
<% end %>

<h2>Usertyping Stats</h2>

<p>
  <ul>
    <% if @n_of_collections.present? %>
      <li>The number of collections: <span style='font-size: 200%;'><%= @n_of_collections =%></span></li>
    <% end %>
    <% if @n_of_users.present? %>
      <li>The number of users: <span style='font-size: 200%;'><%= @n_of_users =%></span></li>
    <% end %>
  </ul>
</p>