config/routes.rb
Rails.application.routes.draw do
  get 'users/show'

  devise_for :users
  resources :users, :only => [:show], :path => 'u' do
    resources :collections, :except => [:index, :new], :path => '/' do
      resources :texts, :except => [:index, :new]

      member do
        get 'play'
      end
    end
  end
  resources :collections, :only => [:index]

  root 'welcome#index'

end

app/models/text.rb
class Text < ActiveRecord::Base
  belongs_to :collection

  validates :title,
    :presence => true,
    :uniqueness => {
      :scope => [:collection_id],
      :case_sensitive => false
    }

  validates :body, :presence => true

  def self.find(query)
    self.find_by_title(query) || super(query)
  end

  def to_param
    "#{self.title}"
  end
end

app/controllers/texts_controller.rb
class TextsController < ApplicationController
  before_action :set_text, only: [:show, :edit, :update, :destroy]
  before_action :set_user, :set_collection
  before_action :authenticate_user, only: [:create, :edit, :update, :destroy]

  # GET /texts
  # GET /texts.json
  def index
    @texts = Text.all
  end

  # GET /texts/1
  # GET /texts/1.json
  def show
  end

  # GET /texts/1/edit
  def edit
  end

  # POST /texts
  # POST /texts.json
  def create
    @text = Text.new(text_params)

    respond_to do |format|
      if @text.save
        format.html { redirect_to user_collection_path(@user, @collection), notice: 'Text was successfully created.' }
        format.json { render :show, status: :created, location: @text }
      else
        format.html { render :new }
        format.json { render json: @text.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /texts/1
  # PATCH/PUT /texts/1.json
  def update
    respond_to do |format|
      if @text.update(text_params)
        format.html { redirect_to user_collection_text_path(@user, @collection, @text), notice: 'Text was successfully updated.' }
        format.json { render :show, status: :ok, location: @text }
      else
        format.html { render :edit }
        format.json { render json: @text.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /texts/1
  # DELETE /texts/1.json
  def destroy
    @text.destroy
    respond_to do |format|
      format.html { redirect_to user_collection_url(@user, @collection), notice: 'Text was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_text
      @text = Text.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def text_params
      params.require(:text).permit(:title, :body, :description, :collection_id)
    end

    def set_collection
      @collection = Collection.find(params[:collection_id])
    end

    def set_user
      @user = User.find(params[:user_id])
    end

    def authenticate_user
      @user = User.find(params[:user_id])
      if @user != current_user
        redirect_to user_collections_url, notice: 'You have no permission'
      end
    end
end

app/helpers/texts_helper.rb
module TextsHelper
end

app/views/texts/_form.html.erb
<%= form_for([@user, @collection, @text]) do |f| %>
  <% if @text.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@text.errors.count, "error") %> prohibited this text from being saved:</h2>

      <ul>
      <% @text.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
      <%= f.text_field :title, :class => 'mdl-textfield__input' %>
      <%= f.label :title, :class => 'mdl-textfield__label' %>
    </div>
  </div>
  <div>
    <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
      <%= f.text_area :body, :class => 'mdl-textfield__input' %>
      <%= f.label :body, :class => 'mdl-textfield__label' %>
    </div>
  </div>
  <div>
    <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
      <%= f.text_area :description, :class => 'mdl-textfield__input' %>
      <%= f.label :description, :class => 'mdl-textfield__label' %>
    </div>
  </div>
  <div class="field">
    <%= f.hidden_field :collection_id %>
  </div>
  <div class="actions">
    <%= f.submit 'Submit', :class => 'mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--accent'  %>
  </div>
<% end %>

app/views/texts/edit.html.erb
<h1>Editing Text</h1>

<%= render 'form' %>

<%= link_to 'Show', user_collection_text_path(@user, @collection, @text) %> |
<%= link_to 'Back', user_collection_path(@user, @collection) %>

app/views/texts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Texts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th>Description</th>
      <th>Collection</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @texts.each do |text| %>
      <tr>
        <td><%= text.title %></td>
        <td><%= text.body %></td>
        <td><%= text.description %></td>
        <td><%= text.collection %></td>
        <td><%= link_to 'Show', user_collection_text_path(@user, @collection, text) %></td>
        <td><%= link_to 'Edit', edit_user_collection_text_path(@user, @collection, text) %></td>
        <td><%= link_to 'Destroy', user_collection_text_path(@user, @collection, text), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Text', new_user_collection_text_path %>

app/views/texts/new.html.erb
<h1>New Text</h1>

<%= render 'form' %>

<%= link_to 'Back', user_collection_path(@user, @collection) %>

app/views/texts/show.html.erb
<h1><%= @user.username %> / <%= @collection.title %> / <%= @text.title %> </h1>

<p>
  <strong>Body:</strong>
  <%= @text.body %>
</p>

<p>
  <strong>Description:</strong>
  <%= @text.description %>
</p>

<% if user_signed_in? and @user == current_user %>
  <%= link_to 'Edit', edit_user_collection_text_path(@user, @collection, @text) %> |
<% end %>

<%= link_to 'Back', user_collection_path(@user, @collection) %>